spring.application.name=demo

# Conexion a SQL Server
spring.datasource.url=${AZURE_SQL_URL}
spring.datasource.username=${AZURE_SQL_USER}
spring.datasource.password=${AZURE_SQL_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Propiedades de JWT
# Duracion 5 horas
jwt.secret=${JWT_SECRET}
jwt.expiration=18000000